# syntax=docker/dockerfile:1

FROM oven/bun:1.3.9 AS deps
WORKDIR /app
RUN bun --version
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

FROM oven/bun:1.3.9 AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=deps /app/node_modules ./node_modules
COPY . .
CMD ["bun", "--env-file=.env", "scripts/bullmq-worker.ts"]
